repos:
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  -   id: black
      language_version: python3.10

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  -   id: flake8

- repo: https://github.com/pycqa/isort
  rev: 5.5.4
  hooks:
  -   id: isort
      files: "\\.(py)$"
      args: [--settings-path=pyproject.toml]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0  # Use the ref you want to point at
  hooks:
  -   id: trailing-whitespace

- repo: https://github.com/PyCQA/autoflake
rev: v2.2.0
hooks:
  -   id: autoflake

